---
language: python
services: docker

install:
  # Install molecule
  - pip install molecule yamllint ansible-lint docker

script:
  - travis_wait 30 molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
